name       : manaplus
version    : 1.8.4.14
release    : 10
source     :
    - https://gitlab.com/manaplus/manaplus/-/archive/v1.8.4.14/manaplus-v1.8.4.14.tar.bz2 : 7c37ca82eb07e7d40f5a7d35e9d39d697f502ab8eed51a95690e34968f2141f6
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
component  : games.mmo
summary    : Advanced 2D MMORPG client for The Mana World and Evol Online
description: |
    ManaPlus is extended client for Evol Online, The Mana World and similar servers based on the eAthena fork. As a 2D style game, Evol Online creates a fantasy environment. The Mana World (TMW) is an effort to create an MMORPG. TMW uses 2D graphics and creates a large and diverse interactive world.
builddeps  :
    - pkgconfig(SDL2_gfx)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(glu)
    - pkgconfig(harfbuzz)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - dejavu-fonts-ttf
    - liberation-fonts-ttf
rundeps    :
    - dejavu-fonts-ttf
    - liberation-fonts-ttf
    - xdg-utils
setup      : |
    %reconfigure --with-sdl2 --enable-unittests
build      : |
    %make
install    : |
    %make_install

    # Use available system fonts
    rm -f $installdir/usr/share/manaplus/data/fonts/dejavu*.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf $installdir/usr/share/manaplus/data/fonts/dejavusans-bold.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf $installdir/usr/share/manaplus/data/fonts/dejavusans.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf $installdir/usr/share/manaplus/data/fonts/dejavusansmono-bold.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf $installdir/usr/share/manaplus/data/fonts/dejavusansmono.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-Bold.ttf $installdir/usr/share/manaplus/data/fonts/dejavuserifcondensed-bold.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed.ttf $installdir/usr/share/manaplus/data/fonts/dejavuserifcondensed.ttf
    rm -f $installdir/usr/share/manaplus/data/fonts/liberation*.ttf
    ln -s /usr/share/fonts/Liberation/LiberationSans-Bold.ttf $installdir/usr/share/manaplus/data/fonts/liberationsans-bold.ttf
    ln -s /usr/share/fonts/Liberation/LiberationSans-Regular.ttf $installdir/usr/share/manaplus/data/fonts/liberationsans.ttf
    ln -s /usr/share/fonts/Liberation/LiberationMono-Bold.ttf $installdir/usr/share/manaplus/data/fonts/liberationsansmono-bold.ttf
    ln -s /usr/share/fonts/Liberation/LiberationMono-Regular.ttf $installdir/usr/share/manaplus/data/fonts/liberationsansmono.ttf
check      : |
    %make check
