name       : manaplus
version    : 1.6.30
release    : 1
source     :
    - https://gitlab.com/manaplus/manaplus/repository/archive.tar.gz?ref=v1.6.7.30 : 533afba39ff5bd38e54fe091146138b5bd7056e0789ba7b42e94768f68204d9a
license    : GPL-2.0
component  : games.mmo
summary    : The Mana Plus Client
description: |
    The Mana Plus Client
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(SDL_gfx)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
    - pkgconfig(SDL_ttf)
    - physfs-devel
rundeps:
    - xdg-utils
setup : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
