name       : manaplus
version    : 1.2.1.21
release    : 2
source     :
    - git|https://gitlab.com/manaplus/manaplus : v1.7.1.21
license    : GPL-2.0
component  : games.mmo
summary    : The Mana Plus Client
description: |
    The Mana Plus Client
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(SDL_gfx)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
    - pkgconfig(SDL_ttf)
    - physfs-devel
rundeps    :
    - xdg-utils
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
