name       : manaplus
version    : 1.7.9.2
release    : 4
source     :
    - https://github.com/ManaPlus/ManaPlus/archive/v1.7.9.2.tar.gz : 20563c01101cd420601a63d1d547ffa51efbc985bede4b5d364d731448836b1a
license    : GPL-2.0
component  : games.mmo
summary    : Advanced 2D MMORPG client for The Mana World and Evol Online
description: "ManaPlus is extended client for Evol Online, The Mana \nWorld and similar servers based on the eAthena fork. As a 2D style game,\nEvol Online creates a fantasy environment. The Mana World\
    \ (TMW) is an\neffort to create an MMORPG. TMW uses 2D graphics and creates a large and\ndiverse interactive world.\n"
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(harfbuzz)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(SDL2_gfx)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
    - pkgconfig(SDL2_ttf)
    - dejavu-fonts-ttf
    - liberation-fonts-ttf
rundeps    :
    - dejavu-fonts-ttf
    - liberation-fonts-ttf
    - xdg-utils
setup      : |
    %reconfigure --with-sdl2
build      : |
    %make
install    : |
    %make_install

    # Use available system fonts
    rm -f $installdir/usr/share/manaplus/data/fonts/dejavu*.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf $installdir/usr/share/manaplus/data/fonts/dejavusans-bold.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf $installdir/usr/share/manaplus/data/fonts/dejavusans.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf $installdir/usr/share/manaplus/data/fonts/dejavusansmono-bold.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf $installdir/usr/share/manaplus/data/fonts/dejavusansmono.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-Bold.ttf $installdir/usr/share/manaplus/data/fonts/dejavuserifcondensed-bold.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed.ttf $installdir/usr/share/manaplus/data/fonts/dejavuserifcondensed.ttf
    rm -f $installdir/usr/share/manaplus/data/fonts/liberation*.ttf
    ln -s /usr/share/fonts/Liberation/LiberationSans-Bold.ttf $installdir/usr/share/manaplus/data/fonts/liberationsans-bold.ttf
    ln -s /usr/share/fonts/Liberation/LiberationSans-Regular.ttf $installdir/usr/share/manaplus/data/fonts/liberationsans.ttf
    ln -s /usr/share/fonts/Liberation/LiberationMono-Bold.ttf $installdir/usr/share/manaplus/data/fonts/liberationsansmono-bold.ttf
    ln -s /usr/share/fonts/Liberation/LiberationMono-Regular.ttf $installdir/usr/share/manaplus/data/fonts/liberationsansmono.ttf

